# Generated by Django 5.0.3 on 2024-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme_recherche',
            name='id_theme',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
