# Generated by Django 5.0.3 on 2024-03-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_remove_theme_recherche_equipe_recherche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoire',
            name='Partenaire',
        ),
        migrations.AddField(
            model_name='equipe_recherche',
            name='laboratoire',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Equipe_recherche', to='publication.laboratoire'),
        ),
        migrations.AddField(
            model_name='equipe_recherche',
            name='theme',
            field=models.CharField(default='', max_length=255),
        ),
    ]
