# Generated by Django 5.0.3 on 2024-05-14 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_alter_projet_id_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
