# Generated by Django 5.0.3 on 2024-04-03 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_club_publication_club_membreclub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annuaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='annuaire_photos/')),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administration_Annuaire',
            fields=[
                ('annuaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.annuaire')),
                ('mot_cle', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100)),
            ],
            bases=('publication.annuaire',),
        ),
        migrations.CreateModel(
            name='Alumnie_Annuaire',
            fields=[
                ('annuaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.annuaire')),
                ('promotion', models.IntegerField(blank=True)),
            ],
            bases=('publication.annuaire',),
        ),
        migrations.CreateModel(
            name='Enseignant_Annuaire',
            fields=[
                ('annuaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.annuaire')),
                ('grade', models.CharField(blank=True, choices=[('professeur', 'Professeur'), ('maître de conférences A', 'Maître de conférences A'), ('maître de conférences B', 'Maître de conférences B')], max_length=50)),
            ],
            bases=('publication.annuaire',),
        ),
    ]
