# Generated by Django 5.0.3 on 2024-04-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_annuaire_administration_annuaire_alumnie_annuaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration_annuaire',
            name='mot_cle',
        ),
        migrations.AddField(
            model_name='annuaire',
            name='mot_cle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
