# Generated by Django 5.0.3 on 2024-04-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_question_reponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='auteur',
        ),
    ]
