# Generated by Django 5.0.3 on 2024-03-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_chercheur_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire_labo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
