# Generated by Django 5.0.3 on 2024-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme_recherche',
            name='Equipe_Recherche',
        ),
        migrations.AddField(
            model_name='theme_recherche',
            name='projets',
            field=models.ManyToManyField(related_name='themes', to='publication.projet'),
        ),
    ]
