# Generated by Django 5.0.3 on 2024-03-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_remove_laboratoire_chercheur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoire',
            name='Partenaire',
        ),
    ]
