# Generated by Django 5.0.3 on 2024-03-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0011_alter_laboratoire_partenaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoire',
            name='Partenaire',
        ),
    ]
