# Generated by Django 5.0.3 on 2024-03-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_remove_laboratoire_partenaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme_recherche',
            name='projets',
        ),
        migrations.AddField(
            model_name='partenaire_labo',
            name='laboratoire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.laboratoire'),
        ),
        migrations.AddField(
            model_name='projet',
            name='themes',
            field=models.ManyToManyField(related_name='themes', to='publication.theme_recherche'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='equipeRecherche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chercheurs', to='publication.equipe_recherche'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_adminstrateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_chercheur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_directeur_relex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_editeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_responsable_fablab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipe_projet',
            name='Chercheur',
            field=models.ManyToManyField(related_name='equipe_projet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipe_projet',
            name='id_equipe_projet',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipe_recherche',
            name='id_equipe_recherche',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Chercheur',
        ),
    ]
