# Generated by Django 5.0.3 on 2024-03-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_remove_theme_recherche_projets'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='themes',
            field=models.ManyToManyField(related_name='themes', to='publication.theme_recherche'),
        ),
    ]
