# Generated by Django 5.0.3 on 2024-03-28 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0016_utilisateur_contact_utilisateur_is_adminstrateur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chercheur',
        ),
        migrations.CreateModel(
            name='Chercheur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('publication.utilisateur',),
        ),
        migrations.CreateModel(
            name='ChercheurEquipe',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chercheurs', to='publication.equipe_recherche')),
            ],
            options={
                'verbose_name': 'Chercheur',
                'verbose_name_plural': 'Chercheurs',
            },
            bases=('publication.chercheur',),
        ),
    ]
