# Generated by Django 5.0.3 on 2024-04-17 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppFablab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandemateriel',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piece',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFablab.category'),
        ),
        migrations.AddField(
            model_name='demandemateriel',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFablab.piece'),
        ),
        migrations.AddField(
            model_name='usersavedpiece',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFablab.piece'),
        ),
        migrations.AddField(
            model_name='usersavedpiece',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedpiece',
            unique_together={('user', 'piece')},
        ),
    ]
