# Generated by Django 5.0.3 on 2024-03-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Demande_Partenariat',
            fields=[
                ('id_partenariat', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=50)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id_devis', models.IntegerField(primary_key=True, serialize=False)),
                ('etat', models.CharField(max_length=50)),
                ('montant', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe_Projet',
            fields=[
                ('id_equipe_projet', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe_Recherche',
            fields=[
                ('id_equipe_recherche', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('prix', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id_partenaire', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.utilisateur')),
            ],
            bases=('publication.utilisateur',),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('equipe_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.equipe_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id_publication', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/')),
                ('etat', models.CharField(max_length=50)),
                ('type_publication', models.CharField(max_length=50)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Theme_Recherche',
            fields=[
                ('id_theme', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Equipe_Recherchee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.equipe_recherche')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id_laboratoire', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Partenaire', models.ManyToManyField(related_name='Labo_chercheur', to='publication.partenaire')),
                ('Chercheur', models.ManyToManyField(related_name='Labo_chercheur', to='publication.chercheur')),
            ],
        ),
        migrations.AddField(
            model_name='equipe_projet',
            name='Chercheur',
            field=models.ManyToManyField(related_name='equipes_projet', to='publication.chercheur'),
        ),
    ]
