# Generated by Django 5.0.3 on 2024-03-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_rename_equipe_recherchee_theme_recherche_equipe_recherche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='id_utilisateur',
            new_name='id',
        ),
    ]
