# Generated by Django 5.0.3 on 2024-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_rename_id_utilisateur_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
