# Generated by Django 5.0.3 on 2024-03-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_equipe_projet_laboratoire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chercheur',
            name='equipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chercheurs', to='publication.equipe_recherche'),
        ),
    ]
