# Generated by Django 5.0.3 on 2024-03-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='id_categorie',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id_publication',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
