# Generated by Django 5.0.3 on 2024-03-27 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_laboratoire_partenaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoire',
            name='Chercheur',
        ),
    ]
