# Generated by Django 5.0.3 on 2024-03-27 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_remove_laboratoire_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire_labo',
            name='laboratoire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.laboratoire'),
        ),
    ]
