# Generated by Django 5.0.3 on 2024-03-30 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeMateriel',
            fields=[
                ('id_demandeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.TextField()),
                ('Role', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(max_length=50)),
                ('responsable_fablab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceElect',
            fields=[
                ('id_demandeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.TextField()),
                ('Role', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(max_length=50)),
                ('demande_materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_pieces', to='fablab.demandemateriel')),
            ],
        ),
    ]
