# Generated by Django 5.0.3 on 2024-03-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0002_category_pieceelect_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandemateriel',
            name='Role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pieceelect',
            name='Role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
